spring.application.name=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/jostore
spring.datasource.username=jostore
spring.datasource.password=jostore_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
